const charactersActionTypes = {
  LOAD_CHARACTERS_START: 'LOAD_CHARACTERS_START',
  LOAD_CHARACTERS_SUCCESS: 'LOAD_CHARACTERS_SUCCESS',
  LOAD_CHARACTERS_FAILURE: 'LOAD_CHARACTERS_FAILURE',
};

export default charactersActionTypes;
