const starshipsActionTypes = {
  LOAD_STARTSHIPS_START: 'LOAD_STARTSHIPS_START',
  LOAD_STARTSHIPS_SUCCESS: 'LOAD_STARTSHIPS_SUCCESS',
  LOAD_STARTSHIPS_FAILURE: 'LOAD_STARTSHIPS_FAILURE',
};

export default starshipsActionTypes;
