const speciesActionTypes = {
  LOAD_SPECIES_START: 'LOAD_SPECIES_START',
  LOAD_SPECIES_SUCCESS: 'LOAD_SPECIES_SUCCESS',
  LOAD_SPECIES_FAILURE: 'LOAD_SPECIES_FAILURE',
};

export default speciesActionTypes;
